<a href="https://colab.research.google.com/github/Julia-Vanyarina/-Laboratornay-colab/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F1NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


1.1. Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n


In [ ]:
n=int(input())
Z = np.zeros(n)
print(Z)

4
[0. 0. 0. 0.]


1.2 Посчитайте размер матрицы Z в байтах и выведите его на печать.

In [ ]:
Z=np.zeros((10,10))
print(Z.itemsize*Z.size)

800


1.3. Считайте 2 числа:
n - размер Numpy вектора
x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.

In [ ]:
n=int(input())
x=int(input())
z = np.zeros(n)
z[x]=1
print(z)

14
5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


1.4Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1.

In [ ]:
n=int(input())
m=int(input())
z=np.arange(n, m+1, 1)
print(z)

12
56
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56]


1.5. Дан вектор Z. "Разверните" его.

In [ ]:
z = np.array([1, 2, 3, 4])
z = z[::-1]
print(z)

[4 3 2 1]


1.6. Считайте 3 числа:

n - количество элементов матрицы

 m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется
пустых мест.

In [ ]:
n=int(input())
m=int(input())
k=int(input())
z=np.arange(n).reshape(m,k)
print(z)

9
3
3
[[0 1 2]
 [3 4 5]
 [6 7 8]]


1.7. Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов.

In [ ]:
z=np.array(list(map(int, input().split()))) 
NonZerros=np.nonzero(z)
print(NonZerros)

1 2 0 0 4 0
(array([0, 1, 4]),)


1.8. Считайте число n. Создайте единичную матрицу размера n, сохраните результат в
переменную Z.

In [ ]:
n=int(input())
z= np.eye(n)
print(z)

3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.9 Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел Numpy
с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и
сохраните результат в переменную Z.


In [ ]:
n=int(input())
m=int(input())
l=int(input())
np.random.seed(42)
z=np.random.random((n,m,l))
print(z)

2
2
2
[[[0.37454012 0.95071431]
  [0.73199394 0.59865848]]

 [[0.15601864 0.15599452]
  [0.05808361 0.86617615]]]


1.10. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1). Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [ ]:
n=int(input())
m=int(input())
np.random.seed(42)
z=np.random.random((n,m))
print(z.min())
print(z.max())

10
10
0.005522117123602399
0.9868869366005173


1.11. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42).Создайте матрицу n*m из случайных чисел (от 0 до 1). Выведите на печать значение среднего для всей матрицы.

In [ ]:
n=int(input())
m=int(input())
np.random.seed(42)
z=np.random.random((n,m))
print(z.mean())

12
6
0.46798212705144554


1.12. Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z. A и B могут содержать как int, так и float.

In [ ]:
A=np.array(list(map(float, input().split()))) 
B=np.array(list(map(float, input().split()))) 
z= np.dot(A, B)
print(z)

1 3 5 7 9
-2 4 -6 8 -10
-54.0


1.13. Даны 2 матрицы: A и B. Найдите произведение матриц и сохраните его в переменную Z.
Если найти произведение матриц невозможно, то запишите в Z строку:
Упс! Что-то пошло не так...

In [ ]:
A=np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B= np.array([
 [11.5],
 [12.5],
 [13.5]
])
try:
  z=np.dot(A, B)
  print(z)
except:
  print("Упс! Что-то пошло не так...")

[[ 77. ]
 [189.5]]


1.14. Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

In [3]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [4]:
Z = np.array([-10, -5, 0, 5, 10])
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[-10  -5   0  -5  10]


1.15.Подсчитать произведение ненулевых элементов на диагонали прямоугольной
матрицы. Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [5]:
Z = np.diag(np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]), k=0)
NonZerros=np.nonzero(Z)
Z=Z[NonZerros]
Z=Z.prod()
print(Z)

3
